name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: "pages"
      cancel-in-progress: false
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Publish .NET Core Project
      run: dotnet publish BlazorApp/BlazorApp.csproj -c Release -o release --nologo
      
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Change base-tag in index.html
      run: sed -i 's/<base href="\/"/<base href="\/SecurityOfficeWebApp\/"/' release/wwwroot/index.html
      
    - name: Replace Firebase Config
      run: |
        sed -i "s/%FIREBASE_API_KEY%/${{ secrets.FIREBASE_API_KEY }}/g" release/wwwroot/index.html
        sed -i "s/%FIREBASE_AUTH_DOMAIN%/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g" release/wwwroot/index.html
        sed -i "s/%FIREBASE_PROJECT_ID%/${{ secrets.FIREBASE_PROJECT_ID }}/g" release/wwwroot/index.html
        sed -i "s/%FIREBASE_STORAGE_BUCKET%/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g" release/wwwroot/index.html
        sed -i "s/%FIREBASE_MESSAGING_SENDER_ID%/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g" release/wwwroot/index.html
        sed -i "s/%FIREBASE_APP_ID%/${{ secrets.FIREBASE_APP_ID }}/g" release/wwwroot/index.html
        sed -i "s/%FIREBASE_MEASUREMENT_ID%/${{ secrets.FIREBASE_MEASUREMENT_ID }}/g" release/wwwroot/index.html
    
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: release/wwwroot
        branch: gh-pages
        clean: true