name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      # Create Firebase config
      - name: Create Firebase Config
        run: |
          echo "window.firebaseConfig = {
            apiKey: \"${{ secrets.FIREBASE_API_KEY }}\",
            authDomain: \"${{ secrets.FIREBASE_AUTH_DOMAIN }}\",
            projectId: \"${{ secrets.FIREBASE_PROJECT_ID }}\",
            storageBucket: \"${{ secrets.FIREBASE_STORAGE_BUCKET }}\",
            messagingSenderId: \"${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}\",
            appId: \"${{ secrets.FIREBASE_APP_ID }}\"
          };" > BlazorApp/wwwroot/firebase-config.js

      - name: Publish .NET Project
        run: dotnet publish BlazorApp/BlazorApp.csproj -c Release -o release --nologo

      # Ensure firebase.js exists in the output
      - name: Ensure firebase.js exists
        run: |
          echo "Checking for firebase.js file..."
          find BlazorApp -name "firebase.js" -type f
          
          # Create js directory if it doesn't exist
          mkdir -p release/wwwroot/js/
          
          # Try to find and copy the file, with fallback options
          if [ -f "BlazorApp/wwwroot/js/firebase.js" ]; then
            echo "Found at BlazorApp/wwwroot/js/firebase.js"
            cp BlazorApp/wwwroot/js/firebase.js release/wwwroot/js/
          elif [ -f "BlazorApp/wwwroot/JS/firebase.js" ]; then
            echo "Found at BlazorApp/wwwroot/JS/firebase.js (case difference)"
            cp BlazorApp/wwwroot/JS/firebase.js release/wwwroot/js/
          elif [ -f "BlazorApp/wwwroot/firebase.js" ]; then
            echo "Found at BlazorApp/wwwroot/firebase.js"
            cp BlazorApp/wwwroot/firebase.js release/wwwroot/js/
          else
            echo "Could not find firebase.js file. Creating a minimal version."
            cat > release/wwwroot/js/firebase.js << 'EOL'
            // Initialize Firebase
            firebase.initializeApp(window.firebaseConfig);

            window.firebaseSignInWithEmailAndPassword = async (email, password) => {
                try {
                    const userCredential = await firebase.auth().signInWithEmailAndPassword(email, password);
                    return userCredential.user.uid;
                } catch (error) {
                    console.error("Sign in error:", error);
                    throw error;
                }
            };

            window.firebaseSignOut = async () => {
                await firebase.auth().signOut();
            };

            window.firebaseGetCurrentUser = async () => {
                return new Promise((resolve) => {
                    firebase.auth().onAuthStateChanged(user => {
                        if (user) {
                            resolve({
                                uid: user.uid,
                                email: user.email,
                                displayName: user.displayName,
                                token: user.auth.currentUser.accessToken
                            });
                        } else {
                            resolve(null);
                        }
                    });
                });
            };
            EOL
          fi
          
          # Verify the file was created
          ls -la release/wwwroot/js/firebase.js


      # Add .nojekyll file
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      # Update base href
      - name: Update base href
        run: sed -i 's|<base href="/" />|<base href="/SecurityOfficeWebApp/" />|g' release/wwwroot/index.html

      # Create 404.html for SPA routing
      - name: Create 404.html for SPA routing
        run: |
          cat > release/wwwroot/404.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
              <meta charset="utf-8">
              <title>Dunleavy Security App</title>
              <script type="text/javascript">
                  var segmentCount = 1;
                  var l = window.location;
                  l.replace(
                      l.protocol + '//' + l.hostname + (l.port ? ':' + l.port : '') +
                      l.pathname.split('/').slice(0, 1 + segmentCount).join('/') + '/?p=/' +
                      l.pathname.slice(1).split('/').slice(segmentCount).join('/').replace(/&/g, '~and~') +
                      (l.search ? '&' + l.search.slice(1).replace(/&/g, '~and~') : '') +
                      l.hash
                  );
              </script>
          </head>
          <body>
              Redirecting...
          </body>
          </html>
          EOL

      # Add redirect handling script to index.html
      - name: Add redirect script to index.html
        run: |
          sed -i '/<head>/a \
              <script type="text/javascript">\
                  (function(l) {\
                      if (l.search[1] === "p") {\
                          var decoded = l.search.slice(1).split("&").map(function(s) { \
                              return s.replace(/~and~/g, "&")\
                          }).join("?");\
                          window.history.replaceState(null, null,\
                              l.pathname.slice(0, -1) + decoded + l.hash\
                          );\
                      }\
                  }(window.location))\
              </script>' release/wwwroot/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
          branch: gh-pages
