name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Add these permissions
    permissions:
      contents: write
      pages: write
      packages: read
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      # Configure NuGet for GitHub Packages
      - name: Setup NuGet Auth
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/dunleavy-meats/index.json \
            --name github \
            --username dunleavy-meats \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text

      # Create Firebase config
      - name: Create Firebase Config
        run: |
          echo "window.firebaseConfig = {
            apiKey: \"${{ secrets.FIREBASE_API_KEY }}\",
            authDomain: \"${{ secrets.FIREBASE_AUTH_DOMAIN }}\",
            projectId: \"${{ secrets.FIREBASE_PROJECT_ID }}\",
            storageBucket: \"${{ secrets.FIREBASE_STORAGE_BUCKET }}\",
            messagingSenderId: \"${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}\",
            appId: \"${{ secrets.FIREBASE_APP_ID }}\"
          };" > BlazorApp/wwwroot/firebase-config.js

      - name: Publish .NET Project
        run: dotnet publish BlazorApp/BlazorApp.csproj -c Release -o release --nologo

      # Add .nojekyll file
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      # Update base href
      - name: Update base href
        run: sed -i 's|<base href="/" />|<base href="/SecurityOfficeWebApp/" />|g' release/wwwroot/index.html

      # Create 404.html for SPA routing
      - name: Create 404.html for SPA routing
        run: |
          cat > release/wwwroot/404.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
              <meta charset="utf-8">
              <title>Dunleavy Security App</title>
              <script type="text/javascript">
                  var segmentCount = 1;
                  var location = window.location;
                  var baseUrl = location.pathname.slice(0, location.pathname.indexOf('/', 1)) || '';
                  var redirectUrl = baseUrl + '/?route=' +
                      location.pathname.slice(1).split('/').slice(segmentCount).join('/').replace(/&/g, '~and~');
                  if (location.search) {
                      redirectUrl += (redirectUrl.indexOf('?') === -1 ? '?' : '&') + 
                          location.search.slice(1).replace(/&/g, '~and~');
                  }
                  location.replace(redirectUrl + location.hash);
              </script>
          </head>
          <body>
          </body>
          </html>
          EOL

      # Add redirect script to index.html
      - name: Add redirect script to index.html
        run: |
          sed -i '/<head>/a \
              <script type="text/javascript">\
                  (function(l) {\
                      if (l.search && l.search.indexOf("?route=") === 0) {\
                          var route = l.search.slice(7);\
                          route = route.replace(/~and~/g, "&");\
                          history.replaceState(null, null,\
                              l.pathname.slice(0, -1) + (route ? "/" + route : "") + l.hash\
                          );\
                      }\
                  }(window.location))\
              </script>' release/wwwroot/index.html

      # Update service worker assets manifest
      - name: Update service worker assets manifest
        run: |
          cd release/wwwroot
          # Remove 404.html from the service worker assets manifest
          sed -i '/"404.html"/d' service-worker-assets.js

      # Update service worker configuration
      - name: Update service worker configuration
        run: |
          cd release/wwwroot
          # Update the service worker assets manifest
          sed -i '/"undefined"/d' service-worker-assets.js
          sed -i '/"404.html"/d' service-worker-assets.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
